// Runs after `astro build`. Writes dist/sw.js, the service worker that keeps a
// copy of every page, picture and font on the phone so the app opens offline.
// The cache name includes a fingerprint of all the files, so each new deploy
// replaces the old copy the next time the app is opened with internet.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const dist = new URL('../dist/', import.meta.url).pathname;
const skip = new Set(['sw.js', '_headers', '_redirects']);

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const hash = createHash('sha256');
const urls = [];
for (const file of walk(dist).sort()) {
  const rel = relative(dist, file).split(sep).join('/');
  if (skip.has(rel)) continue;
  hash.update(rel).update(readFileSync(file));
  // Pages are fetched as folders ("/aorta/"), not "/aorta/index.html".
  urls.push('/' + rel.replace(/(^|\/)index\.html$/, '$1'));
}
const version = hash.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs. Do not edit by hand.
const CACHE = 'scanclub-${version}';
const FILES = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Pages: try the internet first (so edits show up), but give up after 3 seconds
// and use the saved copy. Everything else: use the saved copy straight away.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;

  if (req.mode === 'navigate') {
    event.respondWith(
      new Promise((resolve) => {
        let settled = false;
        const fallback = () => {
          if (settled) return;
          settled = true;
          resolve(caches.match(req, { ignoreSearch: true }).then((r) => r || caches.match('/')));
        };
        const timer = setTimeout(fallback, 3000);
        fetch(req)
          .then((res) => {
            clearTimeout(timer);
            if (settled) return;
            if (!res.ok) return fallback();
            settled = true;
            resolve(res);
          })
          .catch(() => { clearTimeout(timer); fallback(); });
      }),
    );
    return;
  }

  event.respondWith(caches.match(req, { ignoreSearch: true }).then((r) => r || fetch(req)));
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`sw.js: ${urls.length} files cached, version ${version}`);
